theme: jekyll-theme-minimal
title: Samuel Mercer
description: Wer rastet, der rostet...


# Name of website

# Your name to show in the footer
author: Samuel Mercer

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

